In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
df_train_data = pd.read_csv("train_data.csv")
df_train_data

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318433,318434,6,a,6,X,3,radiotherapy,Q,F,4.0,86499,23.0,Emergency,Moderate,3,41-50,4144.0,11-20
318434,318435,24,a,1,X,2,anesthesia,Q,E,4.0,325,8.0,Urgent,Moderate,4,81-90,6699.0,31-40
318435,318436,7,a,4,X,3,gynecology,R,F,4.0,125235,10.0,Emergency,Minor,3,71-80,4235.0,11-20
318436,318437,11,b,2,Y,3,anesthesia,Q,D,3.0,91081,8.0,Trauma,Minor,5,11-20,3761.0,11-20
318437,318438,19,a,7,Y,5,gynecology,Q,C,2.0,21641,8.0,Emergency,Minor,2,11-20,4752.0,0-10

# DATOS NULOS

In [3]:
(df_train_data.isna().sum()/df_train_data.shape[0]*100).round(2)

case_id                              0.00
Hospital_code                        0.00
Hospital_type_code                   0.00
City_Code_Hospital                   0.00
Hospital_region_code                 0.00
Available Extra Rooms in Hospital    0.00
Department                           0.00
Ward_Type                            0.00
Ward_Facility_Code                   0.00
Bed Grade                            0.04
patientid                            0.00
City_Code_Patient                    1.42
Type of Admission                    0.00
Severity of Illness                  0.00
Visitors with Patient                0.00
Age                                  0.00
Admission_Deposit                    0.00
Stay                                 0.00
dtype: float64

## COLUMNA BED GRADE

In [4]:
# Eliminamos datos nulos Bed Grade

In [5]:
df_td_copy1 = df_train_data.copy()

In [6]:
df_td_copy1 = df_td_copy1.dropna(subset = ["Bed Grade"])

In [7]:
(df_td_copy1.isna().sum()/df_td_copy1.shape[0]*100).round(2)

case_id                              0.00
Hospital_code                        0.00
Hospital_type_code                   0.00
City_Code_Hospital                   0.00
Hospital_region_code                 0.00
Available Extra Rooms in Hospital    0.00
Department                           0.00
Ward_Type                            0.00
Ward_Facility_Code                   0.00
Bed Grade                            0.00
patientid                            0.00
City_Code_Patient                    1.42
Type of Admission                    0.00
Severity of Illness                  0.00
Visitors with Patient                0.00
Age                                  0.00
Admission_Deposit                    0.00
Stay                                 0.00
dtype: float64

## COLUMNA CITY_CODE_PATIENT

In [8]:
# Vamos a revisar si algún paciente que tenga valor nulo en ciudad, lo tiene puesto en alguna de sus visitas:
# Incluimos 2 columnas: 1 que cuente los valores nulos en city y otras los valores no nulos y después filtramos cuando ambos sean > 1:
# Utilizamos tabla de prueba:
df_prueba = df_td_copy1.copy()

In [9]:
df_prueba["Numero_nulos_city"] = df_prueba["City_Code_Patient"].isna().groupby(df_prueba["patientid"]).transform("sum")
df_prueba["Numero_no_nulos_city"] = df_prueba["City_Code_Patient"].notna().groupby(df_prueba["patientid"]).transform("sum")
df_prueba.head(2)

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay,Numero_nulos_city,Numero_no_nulos_city
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10,0,14
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50,0,14

In [10]:
filtro = (df_prueba["Numero_nulos_city"]> 0) & (df_prueba["Numero_no_nulos_city"] > 0)
df_prueba.loc[filtro, :]

Empty DataFrame
Columns: [case_id, Hospital_code, Hospital_type_code, City_Code_Hospital, Hospital_region_code, Available Extra Rooms in Hospital, Department, Ward_Type, Ward_Facility_Code, Bed Grade, patientid, City_Code_Patient, Type of Admission, Severity of Illness, Visitors with Patient, Age, Admission_Deposit, Stay, Numero_nulos_city, Numero_no_nulos_city]
Index: []

Ningún paciente con valores NaN en citycode, ha hecho visitas a hospital en el que le hayan incluido este código, por lo tanto, entendemos que no pertenece a ninguna ciudad que tenga código, por lo que incluiremos una categoría que sea "other". Lo incluimos en copy2

In [11]:
df_td_copy2 = df_td_copy1.copy()
df_td_copy2["City_Code_Patient"] = df_td_copy2["City_Code_Patient"].fillna("other")

In [12]:
(df_td_copy2.isna().sum()/df_td_copy2.shape[0]*100).round(2)

case_id                              0.0
Hospital_code                        0.0
Hospital_type_code                   0.0
City_Code_Hospital                   0.0
Hospital_region_code                 0.0
Available Extra Rooms in Hospital    0.0
Department                           0.0
Ward_Type                            0.0
Ward_Facility_Code                   0.0
Bed Grade                            0.0
patientid                            0.0
City_Code_Patient                    0.0
Type of Admission                    0.0
Severity of Illness                  0.0
Visitors with Patient                0.0
Age                                  0.0
Admission_Deposit                    0.0
Stay                                 0.0
dtype: float64

# INCLUSIÓN DE COLUMNAS

## COLUMNA "CANTIDAD DE VISITAS A HOSPITAL POR PACIENTE"

In [13]:
df_td_copy2["Numero_registros_paciente"] = df_td_copy2["patientid"].map(df_td_copy2["patientid"].value_counts())

In [14]:
df_td_copy2

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Ward_Facility_Code,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Visitors with Patient,Age,Admission_Deposit,Stay,Numero_registros_paciente
0,1,8,c,3,Z,3,radiotherapy,R,F,2.0,31397,7.0,Emergency,Extreme,2,51-60,4911.0,0-10,14
1,2,2,c,5,Z,2,radiotherapy,S,F,2.0,31397,7.0,Trauma,Extreme,2,51-60,5954.0,41-50,14
2,3,10,e,1,X,2,anesthesia,S,E,2.0,31397,7.0,Trauma,Extreme,2,51-60,4745.0,31-40,14
3,4,26,b,2,Y,2,radiotherapy,R,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,7272.0,41-50,14
4,5,26,b,2,Y,2,radiotherapy,S,D,2.0,31397,7.0,Trauma,Extreme,2,51-60,5558.0,41-50,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318433,318434,6,a,6,X,3,radiotherapy,Q,F,4.0,86499,23.0,Emergency,Moderate,3,41-50,4144.0,11-20,1
318434,318435,24,a,1,X,2,anesthesia,Q,E,4.0,325,8.0,Urgent,Moderate,4,81-90,6699.0,31-40,1
318435,318436,7,a,4,X,3,gynecology,R,F,4.0,125235,10.0,Emergency,Minor,3,71-80,4235.0,11-20,1
318436,318437,11,b,2,Y,3,anesthesia,Q,D,3.0,91081,8.0,Trauma,Minor,5,11-20,3761.0,11-20,1
318437,318438,19,a,7,Y,5,gynecology,Q,C,2.0,21641,8.0,Emergency,Minor,2,11-20,4752.0,0-10,1

# AGRUPACIONES

## COLUMNA AGE

Agrupamos edades de la siguiente manera:
-0 a 20 años
-21 a 50 años
-51 a 70 años
-71 a 100 años

In [15]:
df_td_copy2.groupby("Age").size()

Age
0-10       6254
11-20     16763
21-30     40828
31-40     63613
41-50     63716
51-60     48497
61-70     33681
71-80     35784
81-90      7887
91-100     1302
dtype: int64

In [16]:
df_td_copy2["Age"] = df_td_copy2["Age"].replace({
    "0-10" : "0-20",
    "11-20" : "0-20",   
    "21-30": "21-50",
    "31-40" : "21-50",
    "41-50" : "21-50",
    "51-60": "51-70",
    "61-70" : "51-70",
    "71-80" : "71-100",
    "81-90" : "71-100",
    "91-100": "71-100"  
})

In [17]:
df_td_copy2.groupby("Age").size()

Age
0-20       23017
21-50     168157
51-70      82178
71-100     44973
dtype: int64

## COLUMNA STAY

In [18]:
# Vamos a agrupar la columna "Stay":
df_td_copy2["Stay"] = df_td_copy2["Stay"].replace({
    "0-10": "Hasta 10 dias",
    "11-20": "Menos de 40 dias",
    "21-30": "Menos de 40 dias",
    "31-40": "Menos de 40 dias",
    "41-50": "Más de 40 días",
    "51-60": "Más de 40 días",
    "61-70": "Más de 40 días",
    "71-80": "Más de 40 días",
    "81-90" : "Más de 40 días",
    "91-100" : "Más de 40 días",
    "More than 100 Days": "Más de 40 días"
})

In [19]:
df_td_copy2.groupby("Stay").size()

Stay
Hasta 10 dias        23602
Menos de 40 dias    220711
Más de 40 días       74012
dtype: int64

# ELIMINAR COLUMNAS

### Información de dataset
- **case_id** : número de caso
- **Hospital_code** : código único para el hospital ([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])
- **Hospital_type_code:** código único para el tipo de Hospital (['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype=object)
- **City_Code_Hospital:** código de la Ciudad del Hospital ([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 13])
- **Hospital_region_code:** código de Región del Hospital (['X', 'Y', 'Z'], dtype=object)
- **Available Extra Rooms in Hospital:** número de habitaciones adicionales disponibles en el Hospital ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 21, 24])
- **Department:** departamento que supervisa el caso (['TB & Chest disease', 'anesthesia', 'gynecology', 'radiotherapy','surgery'], dtype=object)
- **Ward_Type:** código para el tipo de planta (['P', 'Q', 'R', 'S', 'T', 'U'], dtype=object)
- **Ward_Facility_Code:** código para la Instalación de la Sala (['A', 'B', 'C', 'D', 'E', 'F'], dtype=object)
- **Bed Grade:** estado de la cama en la sala ([ 1.,  2.,  3.,  4., nan])
- **patientid:** identificación única del paciente
- **City_Code_Patient:** código de ciudad para la paciente ([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,14., 15., 16., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., nan])
- **Type of Admission:** tipo de Admisión registrado por el Hospital (['Emergency', 'Trauma', 'Urgent'], dtype=object)
- **Severity of Illness:** gravedad de la enfermedad registrada al momento del ingreso (['Extreme', 'Minor', 'Moderate'], dtype=object)
- **Visitors with Patient:** número de acompañantes con el paciente ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 30, 32])
- **Age:** edad (['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70','71-80', '81-90', '91-100'], dtype=object)
- **Admission_Deposit:** depósito en el momento de la admisión (min [1800.0], max[11008.0])
- **Stay:** días de estancia hospitalaria por la paciente (['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70','71-80', '81-90', '91-100', 'More than 100 Days'], dtype=object)

Decidimos eliminar:
- Ward_Facility_Code
- Visitors with Patient
- Admission_Deposit

In [20]:
df_td_copy3 = df_td_copy2.copy()

In [21]:
df_td_copy3 = df_td_copy3.drop(columns = ["Ward_Facility_Code", "Visitors with Patient", "Admission_Deposit"])
df_td_copy3

,case_id,Hospital_code,Hospital_type_code,City_Code_Hospital,Hospital_region_code,Available Extra Rooms in Hospital,Department,Ward_Type,Bed Grade,patientid,City_Code_Patient,Type of Admission,Severity of Illness,Age,Stay,Numero_registros_paciente
0,1,8,c,3,Z,3,radiotherapy,R,2.0,31397,7.0,Emergency,Extreme,51-70,Hasta 10 dias,14
1,2,2,c,5,Z,2,radiotherapy,S,2.0,31397,7.0,Trauma,Extreme,51-70,Más de 40 días,14
2,3,10,e,1,X,2,anesthesia,S,2.0,31397,7.0,Trauma,Extreme,51-70,Menos de 40 dias,14
3,4,26,b,2,Y,2,radiotherapy,R,2.0,31397,7.0,Trauma,Extreme,51-70,Más de 40 días,14
4,5,26,b,2,Y,2,radiotherapy,S,2.0,31397,7.0,Trauma,Extreme,51-70,Más de 40 días,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318433,318434,6,a,6,X,3,radiotherapy,Q,4.0,86499,23.0,Emergency,Moderate,21-50,Menos de 40 dias,1
318434,318435,24,a,1,X,2,anesthesia,Q,4.0,325,8.0,Urgent,Moderate,71-100,Menos de 40 dias,1
318435,318436,7,a,4,X,3,gynecology,R,4.0,125235,10.0,Emergency,Minor,71-100,Menos de 40 dias,1
318436,318437,11,b,2,Y,3,anesthesia,Q,3.0,91081,8.0,Trauma,Minor,0-20,Menos de 40 dias,1
318437,318438,19,a,7,Y,5,gynecology,Q,2.0,21641,8.0,Emergency,Minor,0-20,Hasta 10 dias,1

In [22]:
# Copia con las columnas eliminadas
df_td_copy3.to_csv("train_data_clean.csv")

In [23]:
# Copia sin columnas eliminadas
df_td_copy2.to_csv("train_data_clean_full.csv")